# Generated by Django 5.1.1 on 2024-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('suscriptor', 'Suscriptor')], default='suscriptor', max_length=20),
        ),
    ]
